type: object
required:
  - id
  - name
properties:
  id:
    type: string
    format: uuid
    readOnly: true
  name:
    type: string
  owner:
    type: object
    properties:
      id:
        type: string
        format: uuid
    readOnly: true
    description: License that owns the alternate name
