description:  Supports search and creation of Licenses
parameters:
  - $ref: ../common/parameters/x-okapi-tenant.yaml
get:
  tags:
    - Licenses
  summary: Get a set of license records.
  operationId: getLicenses
  parameters:
    $ref: ../common/parameters/queryParameters.yaml
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            oneOf:
              - $ref: ../components/schemas/LicenseResults.yaml
              - $ref: ../components/schemas/LicenseResultsArray.yaml
    '400':
      description: Bad request error
    '401':
      description: Unauthorized
    '403':
      description: Forbidden
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../common/schemas/GrailsErrorResponse.yaml
post:
  tags:
    - Licenses
  summary: Create license record
  operationId: postLicense
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/License.yaml
    required: true
  responses:
    '201':
      description: Created
      content:
        application/json:
          schema:
            $ref: ../components/schemas/License.yaml
    '400':
      description: Bad request error
    '401':
      description: Unauthorized
    '403':
      description: Forbidden
    '422':
      description: Validation error
      content:
        application/json:
          schema:
            $ref: ../common/schemas/ValidationErrorResponse.yaml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../common/schemas/GrailsErrorResponse.yaml
