description: Supports search of organisations
parameters:
  - $ref: ../common/parameters/x-okapi-tenant.yaml
get:
  tags:
    - Organisations
  summary: Get a set of organisation records
  operationId: getOrgs
  parameters:
    $ref: ../common/parameters/queryParameters.yaml
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            oneOf:
              - $ref: ../components/schemas/OrganisationResults.yaml
              - $ref: ../components/schemas/OrganisationResultsArray.yaml
    '400':
      description: Bad request error
    '401':
      description: Unauthorized
    '403':
      description: Forbidden
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../common/schemas/GrailsErrorResponse.yaml
