get:
  tags:
    - Organisations
  summary: Get a specified organisation record
  operationId: getOrg
  parameters:
    - $ref: ../components/parameters/orgId.yaml
    - $ref: ../common/parameters/x-okapi-tenant.yaml
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Organisation.yaml
    '400':
      description: Bad request error
    '401':
      description: Unauthorized
    '403':
      description: Forbidden
    '404':
      description: Not found error
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../common/schemas/GrailsErrorResponse.yaml
